---
ID: "ef45a518-79df-4943-8336-ad2e7c3a34b9"
Parent: "5996ae17-2739-49f0-a1c8-c5edbe3f0025"
Template: "5996ae17-2739-49f0-a1c8-c5edbe3f0025"
Path: /sitecore/templates/Feature/Demo Shared/Forms/PatternCardActionSettings/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4FDED342-B304-42F7-8091-AE3EB660BA4C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T163800Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
