---
ID: "9040683f-8924-45c7-bc53-1442ea1c8d8a"
Parent: "5996ae17-2739-49f0-a1c8-c5edbe3f0025"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Demo Shared/Forms/PatternCardActionSettings/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T043712Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
