---
ID: "8e414f2e-f658-44a7-a547-2d48a460d551"
Parent: "d154e7eb-4507-4096-b63f-8e6838033ca9"
Template: "e2f11ae2-6c89-411c-879f-9ffbcab98c90"
Path: /sitecore/system/Data Exchange/Demo CRM Dynamics/Pipelines/Dynamics Activities to xConnect Sync Pipelines/Read Activities from Dynamics Pipeline/Set Use Delta Settings
DB: master
BranchID: "f6d87616-5e7c-461a-9d5c-c2bf87deb2a1"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
- ID: "cac1d3bf-041f-46e8-abe1-74701e54554e"
  Hint: ContextValueReader
  Value: "{16AC214F-8E80-428F-B41C-3F423465B319}"
- ID: "cba1e09b-2b35-4165-a7f8-6300e7bce2b5"
  Hint: Operator
  Value: OnOrAfterSelectedDate
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{8E414F2E-F658-44A7-A547-2D48A460D551}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180102T112705Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
