---
ID: "e1a72c77-1354-4f48-bc01-ce7403944ad7"
Parent: "ea496b36-20c8-4e29-a5f4-51744dcd6dac"
Template: "759faf75-ea5f-4ede-bbc2-365f19851b21"
Path: /sitecore/system/Data Exchange/Demo CRM Salesforce/Tenant Settings/Providers/xConnect/XObject Mapping Settings
DB: master
BranchID: "200ef76c-dd0f-4845-9863-b0d4ee1eb36f"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E1A72C77-1354-4F48-BC01-CE7403944AD7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180924T165831Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
