---
ID: "3166bae1-1f53-4a8e-894c-1777a64bdddc"
Parent: "10850f0c-7782-428b-bd3b-69cfd8d03b2e"
Template: "b93f459b-9ddb-4b08-9c5e-b278a8394bda"
Path: /sitecore/system/Data Exchange/Demo CRM Dynamics/Tenant Settings/Providers/SQL/Filter Expressions/Staging
DB: master
BranchID: "f6d87616-5e7c-461a-9d5c-c2bf87deb2a1"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{3166BAE1-1F53-4A8E-894C-1777A64BDDDC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180102T112746Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
