---
ID: "637367d4-1996-49f6-9bc6-7a1bc7d8897f"
Parent: "453425ad-792e-44d9-8e77-5a3875c7a1c7"
Template: "e2f11ae2-6c89-411c-879f-9ffbcab98c90"
Path: /sitecore/system/Data Exchange/Demo CRM Dynamics/Pipelines/Dynamics Contacts to xConnect Sync Pipelines/Read Contacts from Dynamics Pipeline/Set Use Delta Settings
DB: master
BranchID: "f6d87616-5e7c-461a-9d5c-c2bf87deb2a1"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 450
- ID: "cac1d3bf-041f-46e8-abe1-74701e54554e"
  Hint: ContextValueReader
  Value: "{16AC214F-8E80-428F-B41C-3F423465B319}"
- ID: "cba1e09b-2b35-4165-a7f8-6300e7bce2b5"
  Hint: Operator
  Value: OnOrAfterSelectedDate
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{637367D4-1996-49F6-9BC6-7A1BC7D8897F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180102T112648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
