---
ID: "4876a0e8-3f79-4b93-bc23-61e7fc5dfcc5"
Parent: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/templates/Feature/Habitat Home/Accounts/Security Settings/__Standard Values
DB: master
Created: 20190425T160103Z
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171206T135015Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "778ec448-d179-44b2-94c8-c79c8c3c9cb6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190425T160103Z
