---
ID: "ebcffdf1-612b-40c0-8f36-16ebcf9a4b02"
Parent: "7cb57a13-432d-44aa-9300-b3435e985506"
Template: "759faf75-ea5f-4ede-bbc2-365f19851b21"
Path: /sitecore/system/Data Exchange/Demo CRM Dynamics/Tenant Settings/Providers/xConnect/XObject Mapping Settings
DB: master
BranchID: "f6d87616-5e7c-461a-9d5c-c2bf87deb2a1"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{EBCFFDF1-612B-40C0-8F36-16EBCF9A4B02}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180102T112756Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
