---
ID: "288a39aa-c455-48e5-b379-6bc06385f273"
Parent: "ec4dd3f2-590d-404b-9189-2a12679749cc"
Template: "ec4dd3f2-590d-404b-9189-2a12679749cc"
Path: /sitecore/templates/Foundation/Sitecore Demo/Dictionary/DictionaryEntry/__Standard Values
DB: master
Created: 20190425T160048Z
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180419T164302Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f5ecfc32-0ad0-4a32-a770-3c8e37974180"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190425T160048Z
